site_name: Scrapegoat Documentation
site_url: https://chinaiarman.github.io/scrapegoat/

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
      primary: deep purple

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
      primary: deep purple

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths:
            - scrapegoat-core/src
            - scrapegoat-loom/src

nav:
  - Welcome to Scrapegoat: index.md
  - Why use Scrapegoat?: why-scrapegoat.md
  - Installation: installation.md
  - Getting Started: getting-started.md
  - Tutorials:
      - Basic Usage: tutorials/basic-usage.md
      - Advanced Features: tutorials/advanced-features.md
  - Core:
      - Overview: core/index.md
      - Block: core/block.md
      - Command: core/command.md
      - Conditions: core/conditions.md
      - Gardener: core/gardener.md
      - Goat: core/goat.md
      - Interpreter: core/interpreter.md
      - Milkmaid: core/milkmaid.md
      - Milkman: core/milkman.md
      - Node: core/node.md
      - Sheepdog: core/sheepdog.md
      - Shepherd: core/shepherd.md
  - Loom:
      - Overview: loom/index.md
      - Loom: loom/loom.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ChinaiArman/scrapegoat
